### ISSUE TITLE
Suggestion: Notifications on the huntr.dev website itself

### ISSUE THREAD

**Issue by michaellrowley** [418sec/huntr#2089] opened 2021-07-19 11:52 UTC
It'd be cool to see a 'notifications' area on the huntr.dev website so that I don't need to check my emails or manually go through reports to find out if a maintainer/admin has commented on a report.

**Comment by 0xcrypto** [comment] 2021-07-20 04:59
This is already being tracked at https://github.com/418sec/huntr/issues/2035

**Comment by psmoros** [comment] 2021-11-11 13:19
closing as duplicate of #2035 :)

**Closed as completed by psmoros** 2021-11-11 13:19 UTC
