### ISSUE TITLE
As a maintainer, I would like to modify/provide the content that is used in the published advisory.

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2106] opened 2021-08-06 10:23 UTC
Thanks @ehuelsmann for the suggestion!

**Comment by JamieSlome** [comment] 2021-11-08 16:31
@adam-nygate - just to serve as a reminder, we will be including this in the scope of our new work around the automated publishing of CVEs, and maintainer interaction when doing so, i.e. requesting version information, plus further custom text for the content of the published CVE.

**Comment by psmoros** [comment] 2021-11-11 13:03
Update: some of this work will be included in #2157 but most of it in #2161 

I will close this as a duplicate of #2161

**Closed as completed by psmoros** 2021-11-11 13:03 UTC
