### ISSUE TITLE
Unable to disclose for certain repositories.

### ISSUE THREAD

**Issue by michaellrowley** [418sec/huntr#2092] opened 2021-07-28 20:27 UTC
I'm struggling to submit reports for some repositories, I am getting the default ``Please check your GitHub URL and try again...`` error, here are some example URLs:
- ``https://github.com/googleanalytics/ga-dev-tools``
- ``https://github.com/vmcall/dxgkrnl_hook``

**Comment by JamieSlome** [comment] 2021-07-28 21:04
@michaellrowley - sorry to hear you are having this problem...

Are you able to try again once more?

I believe this could be an API rate limit issue on our side, which we will investigate further tomorrow.

**Comment by michaellrowley** [comment] 2021-07-28 23:26
After trying again, it seems to work but take an extended amount of time to load.

Here is a screenshot of the request that seems to be throttling the load:
![BOUNTYMETRICSREQ](https://user-images.githubusercontent.com/13807564/127408824-cf015ce6-d371-4deb-8a72-f0bf6589270d.png)

**Comment by JamieSlome** [comment] 2021-07-29 08:35
@michaellrowley - thanks for the further evidence.

Will look to implement a solution today! 🎉

**Comment by JamieSlome** [comment] 2021-08-03 09:27
After spending some time investigating this issue, we could not pin down the exact cause of the problem, but we do have multiple internal tickets and improvements in place to better gain clarity on what the issue is.

As disclosures against these URLs are still possible, I am going to close this ticket and will make sure to share any updates on this ticket with internal progress made.

Cheers! 🍰

**Closed as completed by JamieSlome** 2021-08-03 09:27 UTC
Labels: bug
