### ISSUE TITLE
Add a visualisation to describe the disclosure process (from start to end)

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2105] opened 2021-08-06 10:20 UTC
Thanks @ehuelsmann for the suggestion!

**Comment by JamieSlome** [comment] 2021-08-27 07:17
@adam-nygate - just a heads up that we have #1999 as well.

**Comment by psmoros** [comment] 2021-11-11 13:42
closing as duplicate of #1999 :)

**Closed as completed by psmoros** 2021-11-11 13:42 UTC
Labels: enhancement
