### ISSUE TITLE
Make Reports Sortable

### ISSUE THREAD

**Issue by dwisiswant0** [418sec/huntr#2171] opened 2021-11-24 21:31 UTC
At this point, I don't know how the report page sorts our reports. It should be sorted by newest to oldest by default, but I'm not sure of that since the reports are grouped by repository - if they weren't grouped it would be easier for us to see the reports ourselves without toggling the repository and showing a list of report titles right away.

**Comment by psmoros** [comment] 2021-11-25 10:29
hey @dwisiswant0! This is a duplicate of #2163 which should be delivered today! :) I will close this as duplicate and feel free to reopen something is our delivery doesn't meet your needs

**Closed as completed by psmoros** 2021-11-25 10:29 UTC
